name: Build Android Executable

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: # 允许在网页上手动点击 "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c
        add-to-path: false

    - name: Run ndk-build
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        echo "NDK Path: $ANDROID_NDK_HOME"
        echo "Checking prebuilt libs..."
        ls -l libs/arm64-v8a/
        
        # 执行核心编译命令
        $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-hack
        path: libs/
