name: Build Android Executable

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c
        add-to-path: false

    - name: Run ndk-build
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        echo "NDK Path: $ANDROID_NDK_HOME"
        ls -l libs/arm64-v8a/
        
        # 【关键修改】加了 NDK_LIBS_OUT=./build_out
        # 让 ndk-build 把成品输出到 build_out，不再清空你的 libs/ 目录！
        $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk NDK_LIBS_OUT=./build_out
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-hack
        path: build_out/
